#!/bin/bash

if [ -z "$JAVA_HOME" ]; then
    PATH="$JAVA_HOME/bin:$PATH"
fi

java -version 2> /dev/null
if [ $? -gt 0 ]; then
    echo "No Java instance has been found."
    exit 1
fi

if [[ "$OSTYPE" = "darwin"* ]]; then
    SCRIPT_DIR=$(dirname `stat -f "$0"`)
    JVMARG="-d32"
    java $JVMARG -version 2> /dev/null
    if [[ $? > 0 ]]; then
        echo "Your Java instance does not support a 32-bit JVM."
        exit 1
    fi
else
    SCRIPT_DIR=$(dirname `readlink -f "$0"`)
fi

java $JVMARG -cp "$SCRIPT_DIR/lib/*" -Dgirinoscope.native.path="$SCRIPT_DIR" org.hihan.girinoscope.ui.UI
