name: girinoscope
version: '1.3.0'

title: Girinoscope
summary: A simple Java graphical user interface for Girino, a Fast Arduino Oscilloscope
description: |
  A simple graphical user interface for Girino, a Fast Arduino Oscilloscope.
  This application is meant to be used with the Girino device
  you will have built by following the instructable made by Caffeinomane
  (http://www.instructables.com/id/Girino-Fast-Arduino-Oscilloscope).
license: Apache-2.0

grade: stable
confinement: strict
base: core18

parts:
  girinoscope:
    plugin: maven
    source: https://github.com/Chatanga/Girinoscope.git
    source-tag: v${SNAPCRAFT_PROJECT_VERSION}
    source-type: git
    maven-options:
      [-Dhttps.protocols=TLSv1.2]

apps:
  girinoscope:
    extensions:
      - gnome-3-28
    command: java -jar $SNAP/jar/Girinoscope-${SNAPCRAFT_PROJECT_VERSION}-dist.jar
    environment:
      _JAVA_OPTIONS: '-Dsun.java2d.opengl=true'
    plugs:
      - home
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - opengl
      - serial-port
