name: girinoscope
version: '1.3.1'

title: Girinoscope
summary: A simple Java graphical user interface for Girino, a Fast Arduino Oscilloscope
description: |
  A simple graphical user interface for Girino, a Fast Arduino Oscilloscope.
  This application is meant to be used with the Girino device
  you will have built by following the instructable made by Caffeinomane
  (http://www.instructables.com/id/Girino-Fast-Arduino-Oscilloscope).
license: Apache-2.0

grade: stable
confinement: strict
base: core18

architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64

parts:
  girinoscope:
    plugin: maven
    source: .
    source-type: local
    maven-options:
      [-Dhttps.protocols=TLSv1.2]
  cleanup:
    after:
      - girinoscope
    plugin: nil
    build-snaps:
      - core18
      - gnome-3-28-1804
    override-prime: |
      set -eux
      for snap in "core18" "gnome-3-28-1804"; do # List all content-snaps and base snaps you're using here
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done
      rm $SNAPCRAFT_PRIME/jar/girinoscope-*.jar # Only the JAR with dependencies is needed.

apps:
  girinoscope:
    extensions:
      - gnome-3-28
    command: java -jar $SNAP/jar/Girinoscope-$SNAPCRAFT_PROJECT_VERSION-dist.jar
    environment:
      _JAVA_OPTIONS: "-Duser.home=$SNAP_USER_DATA -Dsun.java2d.opengl=true"
    plugs:
      - desktop-legacy
      - desktop
      - home
      - opengl
      - serial-port
