name: girinoscope
# Lastest digit distinguishes between Snapcraft builds.
version: '1.4.0'

title: Girinoscope
summary: A simple Java graphical user interface for Girino, a Fast Arduino Oscilloscope
description: |
  A simple graphical user interface for Girino, a Fast Arduino Oscilloscope.
  This application is meant to be used with the Girino device
  you will have built by following the instructable made by Caffeinomane
  (http://www.instructables.com/id/Girino-Fast-Arduino-Oscilloscope).
license: Apache-2.0

grade: stable
confinement: strict
base: core18

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
  - build-on: i386

parts:
  girinoscope:
    plugin: maven
    source: .
    source-type: local
    maven-options:
      # Workaround for:
      #   https://bugs.launchpad.net/snapcraft/+bug/1927312
      #   https://bugs.launchpad.net/ubuntu/+source/openjdk-lts/+bug/1927839
      [-Dhttps.protocols=TLSv1.2]
    stage-packages:
      - default-jre
  cleanup:
    after:
      - girinoscope
    plugin: nil
    build-snaps:
      - core18
      - gnome-3-28-1804
    override-prime: |
      snapcraftctl prime
      # Only the JAR with dependencies is needed.
      rm $SNAPCRAFT_PRIME/jar/girinoscope-*.jar
      # Workaround for:
      #   https://forum.snapcraft.io/t/resolve-package-contains-external-symlinks-error-when-trying-to-snap/2963/23
      # (Old dashboard, useful to know why a release is rejected:
      #   https://dashboard.snapcraft.io/snaps/girinoscope)
      rm -vf usr/lib/jvm/java-11-openjdk-*/lib/security/blacklisted.certs

apps:
  girinoscope:
    extensions:
      - gnome-3-28
    command: java -jar $SNAP/jar/Girinoscope-$SNAPCRAFT_PROJECT_VERSION-dist.jar
    plugs:
      - desktop-legacy
      - desktop
      - home
      - opengl
      - serial-port
