name: girinoscope
version: '1.3.0'

title: Girinoscope
summary: A simple Java graphical user interface for Girino, a Fast Arduino Oscilloscope
description: |
  A simple Java graphical user interface for Girino, a Fast Arduino Oscilloscope.

grade: stable
confinement: strict
base: core18

parts:
  girinoscope:
    plugin: maven
    source: .
    source-type: local
    maven-options:
      [-Dhttps.protocols=TLSv1.2]

apps:
  girinoscope:
    extensions:
      - gnome-3-28
    command: java -jar $SNAP/jar/Girinoscope-$SNAPCRAFT_PROJECT_VERSION-SNAPSHOT-dist.jar
    environment:
      _JAVA_OPTIONS: '-Dsun.java2d.opengl=true'
    plugs:
      - home
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - opengl
      - serial-port
